import { spacing } from '@/constants/theme';
import type { AppearanceContextValue } from '@/lib/appearance';

export function createPetProfileEditorStyles({
  colors,
  getFontFamily,
}: AppearanceContextValue) {
  return {
    card: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: spacing.lg,
      padding: spacing.lg,
    },
    avatar: {
      alignSelf: 'center' as const,
      backgroundColor: colors.border,
      borderRadius: 48,
      height: 96,
      width: 96,
    },
    avatarButton: {
      alignSelf: 'center' as const,
      position: 'relative' as const,
    },
    avatarBadge: {
      alignItems: 'center' as const,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      bottom: 0,
      height: 28,
      justifyContent: 'center' as const,
      position: 'absolute' as const,
      right: -4,
      width: 28,
    },
    avatarHint: {
      color: colors.accent,
      fontFamily: getFontFamily('600'),
      fontSize: 14,
      fontWeight: '600' as const,
      marginTop: spacing.sm,
      textAlign: 'center' as const,
    },
    avatarPlaceholder: {
      alignItems: 'center' as const,
      alignSelf: 'center' as const,
      backgroundColor: colors.border,
      borderRadius: 48,
      height: 96,
      justifyContent: 'center' as const,
      width: 96,
    },
    avatarPlaceholderText: {
      color: colors.accent,
      fontFamily: getFontFamily('600'),
      fontSize: 36,
      fontWeight: '600' as const,
    },
    fieldLabel: {
      color: colors.text,
      fontFamily: getFontFamily('400'),
      fontSize: 15,
      fontWeight: '400' as const,
      marginTop: spacing.lg,
      marginBottom: spacing.xs,
    },
    input: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      color: colors.text,
      fontFamily: getFontFamily('400'),
      fontSize: 15,
      lineHeight: 20,
      minHeight: 52,
      paddingHorizontal: spacing.md,
      paddingVertical: 0,
    },
    inputFocused: {
      borderColor: colors.text,
      borderWidth: 2,
    },
    pickerCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      overflow: 'hidden' as const,
    },
    pickerRow: {
      alignItems: 'center' as const,
      flexDirection: 'row' as const,
      justifyContent: 'space-between' as const,
      minHeight: 52,
      paddingHorizontal: spacing.md,
      paddingVertical: 0,
    },
    pickerRowPressed: {
      opacity: 0.85,
    },
    pickerRowLabel: {
      color: colors.text,
      flex: 1,
      fontFamily: getFontFamily('400'),
      fontSize: 15,
      fontWeight: '400' as const,
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'flex-end' as const,
    },
    modalBackdrop: {
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      bottom: 0,
      left: 0,
      position: 'absolute' as const,
      right: 0,
      top: 0,
    },
    modalSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      overflow: 'hidden' as const,
    },
    modalActions: {
      alignItems: 'center' as const,
      borderTopColor: colors.border,
      borderTopWidth: 1,
      flexDirection: 'row' as const,
      justifyContent: 'space-between' as const,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
    },
    datePickerContainer: {
      backgroundColor: colors.background,
      flexDirection: 'row' as const,
      gap: spacing.sm,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.md,
      width: '100%' as const,
    },
    wheelColumn: {
      flex: 1,
      minWidth: 0,
    },
    wheelColumnLabel: {
      color: colors.textMuted,
      fontFamily: getFontFamily('600'),
      fontSize: 12,
      fontWeight: '600' as const,
      marginBottom: spacing.xs,
      textAlign: 'center' as const,
      textTransform: 'uppercase' as const,
    },
    wheelScroll: {
      maxHeight: 216,
    },
    wheelOption: {
      alignItems: 'center' as const,
      borderRadius: 8,
      justifyContent: 'center' as const,
      marginBottom: spacing.xs,
      minHeight: 36,
      paddingHorizontal: spacing.xs,
    },
    wheelOptionSelected: {
      backgroundColor: colors.accent,
    },
    wheelOptionText: {
      color: colors.text,
      fontFamily: getFontFamily('500'),
      fontSize: 16,
      fontWeight: '500' as const,
      textAlign: 'center' as const,
    },
    wheelOptionTextSelected: {
      color: colors.surface,
      fontFamily: getFontFamily('600'),
      fontWeight: '600' as const,
    },
    modalActionMuted: {
      color: colors.textMuted,
      fontFamily: getFontFamily('600'),
      fontSize: 16,
      fontWeight: '600' as const,
    },
    modalActionPrimary: {
      color: colors.accent,
      fontFamily: getFontFamily('600'),
      fontSize: 16,
      fontWeight: '600' as const,
    },
    photoSourceCard: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      overflow: 'hidden' as const,
    },
    photoSourceTitle: {
      color: colors.text,
      fontFamily: getFontFamily('600'),
      fontSize: 18,
      fontWeight: '600' as const,
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.lg,
      paddingBottom: spacing.md,
      textAlign: 'center' as const,
    },
    photoSourceOption: {
      borderTopColor: colors.border,
      borderTopWidth: 1,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
    },
    photoSourceOptionPressed: {
      opacity: 0.8,
    },
    photoSourceOptionText: {
      color: colors.text,
      fontFamily: getFontFamily('500'),
      fontSize: 16,
      fontWeight: '500' as const,
    },
    photoGrid: {
      flexDirection: 'row' as const,
      flexWrap: 'wrap' as const,
      gap: spacing.sm,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.lg,
    },
    photoGridItem: {
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      height: 92,
      overflow: 'hidden' as const,
      width: 92,
    },
    photoGridItemPressed: {
      opacity: 0.82,
    },
    photoGridImage: {
      height: '100%' as const,
      width: '100%' as const,
    },
    mutedText: {
      color: colors.textMuted,
      fontFamily: getFontFamily('400'),
      fontSize: 14,
      lineHeight: 20,
      marginTop: spacing.sm,
    },
    successText: {
      color: colors.accent,
      fontFamily: getFontFamily('400'),
      fontSize: 14,
      lineHeight: 20,
      marginTop: spacing.md,
    },
    errorText: {
      color: colors.destructive,
      fontFamily: getFontFamily('400'),
      fontSize: 14,
      lineHeight: 20,
      marginTop: spacing.md,
    },
    emptyText: {
      color: colors.textMuted,
      fontFamily: getFontFamily('400'),
      fontSize: 15,
      lineHeight: 22,
      marginTop: spacing.lg,
    },
  };
}
